# Generated by Django 5.1.15 on 2026-06-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_message_voice_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='auth',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='p256dh',
            field=models.TextField(),
        ),
    ]
