# Generated by Django 5.1.15 on 2026-07-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_alter_pushsubscription_options_alter_conversation_id_and_more'),
    ]

    operations = [
    ]