# Generated by Django 5.1.15 on 2026-07-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0010_alter_conversation_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={},
        ),
    ]
