# Generated by Django 5.1.15 on 2026-06-22 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0002_boostrequest_paystack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='verification_fee',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Fee (GH₵) a user must pay to apply for a Verified Student badge', max_digits=8),
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid — Awaiting Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_payment', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verification Request',
                'ordering': ['-created_at'],
            },
        ),
    ]
