# Generated by Django 5.1.15 on 2026-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0003_add_verification_and_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='docs_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='id_photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='liveness_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='selfie_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid', 'Paid — Awaiting Documents'), ('docs_submitted', 'Documents Submitted — Awaiting Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_payment', max_length=20),
        ),
    ]
