# Generated by Django 5.1.15 on 2026-06-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0004_add_verification_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='student_id_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
