# Generated by Django 5.1.15 on 2026-06-23 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_app', '0006_verification_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='support_email',
            field=models.EmailField(default='support@pu-connect.edu.gh', help_text='Public-facing contact/support email shown on help pages and error messages.', max_length=254),
        ),
    ]
