# Generated by Django 5.1.15 on 2026-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
