# Generated by Django 5.1.15 on 2026-06-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile_app', '0004_add_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
