# Generated by Django 5.1.15 on 2026-07-17 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listings_app', '0005_alter_listing_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('scam', 'Scam / Fraud'), ('fake', 'Fake / Misleading'), ('prohibited', 'Prohibited Item'), ('harassment', 'Harassment'), ('inappropriate', 'Inappropriate Content'), ('off_platform', 'Off-Platform Payment Request'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='Listings_ap_status_92b4c2_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['user'], name='Listings_ap_user_id_972a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-created_at'], name='Listings_ap_created_e07a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-created_at'], name='Listings_ap_status_b31e4c_idx'),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Listings_app.listing'),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
