"""
Custom password hasher for PU-Connect.

Uses PBKDF2 with SHA-256 (SHA-2 family) and a cryptographically random
per-password salt.  This satisfies the SHA-2 + salting requirement while
following NIST SP 800-63B and Django's own recommendations.

The iteration count defaults to Django 5.1's built-in value (870 000) but
can be raised at any time via the PW_HASH_ITERATIONS environment variable
without touching code.  Existing hashes stored under the old count remain
verifiable — Django transparently re-hashes on the next successful login.
"""

import os
from django.contrib.auth.hashers import PBKDF2PasswordHasher


class SHA256SaltedHasher(PBKDF2PasswordHasher):
    """
    PBKDF2 + SHA-256 + random salt.

    Algorithm identifier stored in the DB: pbkdf2_sha256
    Salt: 22-character random string generated by Django (128 bits of entropy)
    Digest: SHA-256 (SHA-2 family)
    Iterations: env PW_HASH_ITERATIONS (default 870 000)
    """

    algorithm = "pbkdf2_sha256"
    iterations = int(os.environ.get("PW_HASH_ITERATIONS", 870_000))
    digest_name = "sha256"
