"""
Django settings for pu_mp project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable not set")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

_allowed = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1')
ALLOWED_HOSTS = [h.strip() for h in _allowed.split(',') if h.strip()]

# Security — tighten in production (DEBUG=False)
SECURE_SSL_REDIRECT        = not DEBUG
SESSION_COOKIE_SECURE      = not DEBUG
CSRF_COOKIE_SECURE         = not DEBUG
SECURE_BROWSER_XSS_FILTER  = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_PROXY_SSL_HEADER    = ('HTTP_X_FORWARDED_PROTO', 'https')

_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://pentvarsconnect.com,https://www.pentvarsconnect.com')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _origins.split(',') if o.strip()]

SITE_ID = 1

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'Auth_app',
    'dash_app',
    'Base_app',
    'Profile_app',
    'search_app',
    'chat_app',
    'Listings_app',
    'Reels_app',
    'channels',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

]

# Channels / ASGI config
ASGI_APPLICATION = 'pu_mp.asgi.application'

REDIS_URL = os.environ.get('REDIS_URL', '')

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
            },
        },
    }
else:
    # No Redis configured — use in-process layer (single worker only, no cross-process pub/sub)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.environ.get('GOOGLE_CLIENT_ID'),
            'secret': os.environ.get('GOOGLE_CLIENT_SECRET'),
            'key': ''
        },
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
            'prompt': 'select_account',
        },
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'pu_mp.r2_db_sync.R2DbSyncMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = 'pu_mp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'Base_app.context_processors.pwa_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'pu_mp.wsgi.application'


# Database — two SQLite files
# On GCP VM set DATA_DIR env var to a persistent path e.g. /var/data
# Locally both files sit in the project root
DATA_DIR = os.environ.get('DATA_DIR', BASE_DIR)

DATABASES = {
    # Shared/public data: listings, profiles, categories, auth
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(DATA_DIR, 'global.db'),
        'OPTIONS': {'timeout': 20},
    },
    # Private/user data: messages, conversations, wishlist, notifications, push subscriptions
    'user_db': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(DATA_DIR, 'user.db'),
        'OPTIONS': {'timeout': 20},
    },
}

DATABASE_ROUTERS = ['pu_mp.router.PURouter']



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },


]



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Accra'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "Auth_app" / "static",
    BASE_DIR / "Base_app" / "static",
    BASE_DIR / "dash_app" / "static",
    BASE_DIR / "Listings_app" / "static",
    BASE_DIR / "Profile_app" / "static",
    BASE_DIR / "search_app" / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / "media"

# Cloudflare R2 — media (images, avatars, voice notes)
CF_R2_ACCOUNT_ID = os.environ.get('CF_R2_ACCOUNT_ID', '')
CF_R2_ACCESS_KEY_ID = os.environ.get('CF_R2_ACCESS_KEY_ID', '')
CF_R2_SECRET_ACCESS_KEY = os.environ.get('CF_R2_SECRET_ACCESS_KEY', '')
CF_R2_BUCKET_NAME = os.environ.get('CF_R2_BUCKET_NAME', 'puconnect-media')
CF_R2_PUBLIC_URL = os.environ.get('CF_R2_PUBLIC_URL', '')

# Cloudflare R2 — database backup (separate private bucket, same account credentials)
CF_R2_DB_BUCKET = os.environ.get('CF_R2_DB_BUCKET', 'puconnect-db')

# Web Push (VAPID)
# VAPID_PUBLIC_KEY: raw base64url-encoded uncompressed EC point (no padding)
# VAPID_PRIVATE_KEY: base64-encoded PEM (single line, safe for .env)
VAPID_PUBLIC_KEY  = os.environ.get('VAPID_PUBLIC_KEY', '')
_vapid_priv_b64   = os.environ.get('VAPID_PRIVATE_KEY', '')
import base64 as _b64
VAPID_PRIVATE_KEY = _b64.b64decode(_vapid_priv_b64).decode('utf-8') if _vapid_priv_b64 else ''
VAPID_CLAIMS_EMAIL = os.environ.get('VAPID_CLAIMS_EMAIL', 'puconnect1@gmail.com')

# Paystack
PAYSTACK_SECRET_KEY = os.environ.get('PAYSTACK_SECRET_KEY', '')
PAYSTACK_PUBLIC_KEY = os.environ.get('PAYSTACK_PUBLIC_KEY', '')

# Authentication backends`
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
  
  
    'allauth.account.auth_backends.AuthenticationBackend',
)

# Allauth settings
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = 'none' 

# New way to handle required fields and signup form
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'first_name', 'last_name']

SOCIALACCOUNT_LOGIN_ON_GET = True  # Automatically log in after social authentication
SOCIALACCOUNT_AUTO_SIGNUP = True   # Bypass the intermediate social signup page
SOCIALACCOUNT_QUERY_EMAIL = True   # Ensure we get the email from Google

# Seamless Social Account Connection
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

LOGIN_URL = 'auth:auth_view'
LOGIN_REDIRECT_URL = 'dashboard:dashboard'
LOGOUT_REDIRECT_URL = 'auth:auth_view'

